imports:
    - { resource: "@ProjectUserBundle/Resources/config/services.yml" }

# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

