services:
    admin.playlist:
        class: ProjectBundle\Admin\PlaylistAdmin
        arguments: [~, ProjectBundle\Entity\Playlist, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Playlist }





